spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PrepAce;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true

spring.datasource.username=sa
spring.datasource.password=123456

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=cuuthangnguyen1210@gmail.com
spring.mail.password=nhap o day

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
google.client.id=nhap o day
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port=8080

# SePay Webhook
sepay.api-key=nhap o day
# SePay REST API Token (Dành cho việc chủ động gọi API kiểm tra giao dịch)
sepay.api-token=nhap o day

# PayOS Configuration
payos.client-id=nhap o day
payos.api-key=nhap o day
payos.checksum-key=nhap o day

# Ép Hibernate giữ nguyên chính xác tên bảng viết hoa/viết thường như cấu hình ở @Table
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

# File Upload Limit Configuration
spring.servlet.multipart.max-file-size=3000MB
spring.servlet.multipart.max-request-size=3000MB

# Cloudinary Configuration
cloudinary.cloud-name=desnyjgxp
cloudinary.api-key=nhap o day
cloudinary.api-secret=nhap o day

# ── Gemini AI ──────────────────────────────────────────────────────────────────
# Lấy API key tại: https://aistudio.google.com/app/apikey
gemini.api.url=
gemini.api.key=nhap o day
#openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
#openrouter.api.key=nhap o day
#openrouter.model=openai/gpt-oss-20b:free
#gemini.api.url=https://openrouter.ai/api/v1/chat/completions
#gemini.api.key=nhap o day

spring.task.scheduling.pool.size=5
app.seeder.enabled=false
