spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PrepAce;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true

spring.datasource.username=sa
spring.datasource.password=123456

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=cuuthangnguyen1210@gmail.com
spring.mail.password=yasbyteijcelngxo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
google.client.id=257199987910-2tfe97p674iljqh5uqbgpvqe5b3a55dl.apps.googleusercontent.com
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port=8080

# SePay Webhook
sepay.api-key=5Q5XJOSGR4HQW9ZPMIJYZSABBT4UYLXEJ03RIFA8RXPC3FUN2THCMCDSPOLKO71Z
# SePay REST API Token (Dành cho việc chủ động gọi API kiểm tra giao dịch)
sepay.api-token=2QA7PYLJECXFM9EHNAI1N2ZKIFKHSCKGQYYYAJI3ZHWRDJLKOWJVV8T09TEMO6N0

# PayOS Configuration
payos.client-id=ada6b8b3-3e79-40d7-a086-db1b6c13ebd1
payos.api-key=48bfffd0-98f3-4362-91c3-61ccc52680fb
payos.checksum-key=4913b1c9d7e7f111e60268e8efd5112d5771a4c35122573966267158db0e31f1

# Ép Hibernate giữ nguyên chính xác tên bảng viết hoa/viết thường như cấu hình ở @Table
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

# File Upload Limit Configuration
spring.servlet.multipart.max-file-size=3000MB
spring.servlet.multipart.max-request-size=3000MB

# Cloudinary Configuration
cloudinary.cloud-name=desnyjgxp
cloudinary.api-key=458683156277599
cloudinary.api-secret=PQW71bOcw8f70YZVb-Q1c8oOzIk

# ── Gemini AI ──────────────────────────────────────────────────────────────────
# Lấy API key tại: https://aistudio.google.com/app/apikey
gemini.api.url=
gemini.api.key=
#openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
#openrouter.api.key=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
#openrouter.model=openai/gpt-oss-20b:free
#gemini.api.url=https://openrouter.ai/api/v1/chat/completions
#gemini.api.key=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

spring.task.scheduling.pool.size=5
app.seeder.enabled=false
